### PR TITLE
add A4 PDF format with separation hint instead of scissors

### PR DESCRIPTION
**Pull request by Trim**
Note: this pull request is a draft, because it requires publication of the corresponding bbit.banking-utils pull request first: bbitgmbh/bbit.banking-utils#3

I'll have to update the pull request when version 1.2.0 of bbit.banking-utils is published to update the yarn.lock file with new version.

----

From the _Swiss Implementation Guidelines QR-bill_ document, chapter 3.7
_Notes about the QR-bill in PDF format_:

> If the QR-bill with payment part and receipt or the separate payment part with receipt
> are generated as a PDF document and sent electronically, the A6 format of the
> payment part and the receipt on the left must be indicated by lines. Each of these
> lines must bear the scissors symbol “scissors” or alternatively the instruction “Separate
> before paying in” above the line (outside the payment part).

Translation for the separation hint come from the _Annex D: Multilingual
glossary_ of the same document.

### CODE REVIEW

**Comment by Trim** [comment]
Well, the workflow has failed as expected, because bbit.banking-utils v1.2.0 is not yet available.

To proceed, we need to:

1. Merge PR bbitgmbh/bbit.banking-utils#3 (which creates version 1.2.0 with the new interfaces)
2. Publish the version 1.2 of @bbitgmbh/bbit.banking-utils
3. Update current pull request to have the yarn.lock file updated correctly

Then the workflow should work correctly.

**Comment by thegnuu** [comment]
@Trim I just released @bbitgmbh/bbit.banking-utils v2.0.0 (breaking because I had to remove node12 support) would it be possible for you to rebase your changes and push a commit with running checks?

Thanks a lot!

**Comment by Trim** [comment]
> would it be possible for you to rebase your changes and push a commit with running checks?

Yes, that's done :)

**Comment by thegnuu** [comment]
Great, thanks you @Trim !

I will release a new version asap!

**Comment by thegnuu** [comment]
v3.2.0 is released, I hope everything works in browser environments as well. A few libs were outdated and I updated everything to the newest version, all tests are running so node should work as expected. Unfortunately I don't have a prepared browser test environment at the moment.

**Pull request merged**
